[build]
  command = "npm run build"
  publish = "public"
  functions = "functions"

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18" 
  GATSBY_CPU_COUNT = "2"
  NODE_OPTIONS = "--max_old_space_size=4096"

[[plugins]]
  package = "@netlify/plugin-gatsby"