export const contactContent = {
  'en-US': {
    eyebrow: 'LET’S TALK', title: 'Good things start with a conversation.',
    intro: 'An event, a collaboration or just a question? We would love to hear from you. You do not need to have it all figured out to get in touch.',
    welcome: 'Your ideas. Your questions. Always welcome.',
    direct: 'PREFER A DIRECT CONVERSATION?', whatsapp: 'Chat with us on WhatsApp', emailLink: 'Send us an email', phoneLink: 'Give us a call',
    formEyebrow: 'A LITTLE HELLO GOES A LONG WAY', formTitle: 'What’s on your mind?', formIntro: 'Tell us a little about yourself and how we can help.',
    purpose: 'I’d like to…', purposes: ['Ask a question', 'Plan an event', 'Explore a collaboration', 'Talk about something else'],
    name: 'Your name', namePlaceholder: 'How should we address you?', email: 'Email address', emailPlaceholder: 'you@example.com',
    phone: 'Phone or WhatsApp', optional: 'optional', phoneHint: 'Include your country code if you would like us to contact you here.',
    message: 'Your message', messagePlaceholder: 'Share your idea, ask us a question or tell us what you need. We’re listening.',
    submit: 'Send my message', note: 'Only your name, email and message are required. We use these details to get back to you.',
    nextEyebrow: 'ON THE OTHER SIDE, OUR TEAM', nextTitle: 'We’re here to help you take the next step.',
    steps: [['We listen', 'A first idea or a detailed plan: we start by understanding what you need.'], ['We talk it through', 'We answer your questions and explore the options with you.'], ['We move at your pace', 'Ask for guidance, plan a celebration or open a conversation about working together.']],
    location: 'Based in Punta Cana. Ready to hear from you.',
  },
  es: {
    eyebrow: 'HABLEMOS', title: 'Todo empieza con una conversación.',
    intro: '¿Un evento, una colaboración o simplemente una pregunta? Nos encantará escucharte. No necesitas tenerlo todo resuelto para escribirnos.',
    welcome: 'Tus ideas. Tus preguntas. Siempre bienvenidas.',
    direct: '¿PREFIERES HABLAR DIRECTAMENTE?', whatsapp: 'Conversemos por WhatsApp', emailLink: 'Escríbenos por correo', phoneLink: 'Llámanos',
    formEyebrow: 'UN HOLA ES UN BUEN COMIENZO', formTitle: '¿En qué podemos ayudarte?', formIntro: 'Cuéntanos un poco sobre ti y lo que tienes en mente.',
    purpose: 'Me gustaría…', purposes: ['Hacer una pregunta', 'Organizar un evento', 'Proponer una colaboración', 'Conversar sobre otro tema'],
    name: 'Tu nombre', namePlaceholder: '¿Cómo te llamas?', email: 'Correo electrónico', emailPlaceholder: 'tu@ejemplo.com',
    phone: 'Teléfono o WhatsApp', optional: 'opcional', phoneHint: 'Incluye el código de tu país si prefieres que te contactemos por aquí.',
    message: 'Tu mensaje', messagePlaceholder: 'Comparte tu idea, haznos una pregunta o cuéntanos qué necesitas. Te escuchamos.',
    submit: 'Enviar mi mensaje', note: 'Solo necesitamos tu nombre, correo y mensaje. Usamos estos datos para responderte.',
    nextEyebrow: 'AL OTRO LADO, NUESTRO EQUIPO', nextTitle: 'Estamos aquí para ayudarte a dar el siguiente paso.',
    steps: [['Te escuchamos', 'Una primera idea o un plan detallado: empezamos por entender lo que necesitas.'], ['Conversamos contigo', 'Respondemos tus preguntas y exploramos las opciones a tu lado.'], ['Avanzamos a tu ritmo', 'Puedes pedir orientación, planificar una celebración o conversar sobre cómo trabajar juntos.']],
    location: 'Desde Punta Cana, con ganas de escucharte.',
  },
  pt: {
    eyebrow: 'VAMOS CONVERSAR', title: 'Tudo começa com uma conversa.',
    intro: 'Um evento, uma parceria ou apenas uma pergunta? Vamos adorar ouvir você. Não é preciso ter tudo definido para entrar em contato.',
    welcome: 'Suas ideias. Suas perguntas. Sempre bem-vindas.',
    direct: 'PREFERE FALAR DIRETAMENTE?', whatsapp: 'Converse conosco pelo WhatsApp', emailLink: 'Envie um email', phoneLink: 'Ligue para nós',
    formEyebrow: 'UM OLÁ É UM ÓTIMO COMEÇO', formTitle: 'Como podemos ajudar?', formIntro: 'Conte-nos um pouco sobre você e o que tem em mente.',
    purpose: 'Gostaria de…', purposes: ['Fazer uma pergunta', 'Organizar um evento', 'Propor uma parceria', 'Conversar sobre outro assunto'],
    name: 'Seu nome', namePlaceholder: 'Como você se chama?', email: 'Email', emailPlaceholder: 'voce@exemplo.com',
    phone: 'Telefone ou WhatsApp', optional: 'opcional', phoneHint: 'Inclua o código do país se preferir que entremos em contato por aqui.',
    message: 'Sua mensagem', messagePlaceholder: 'Compartilhe sua ideia, faça uma pergunta ou conte-nos do que precisa. Estamos ouvindo.',
    submit: 'Enviar minha mensagem', note: 'Precisamos apenas de nome, email e mensagem. Usamos esses dados para responder a você.',
    nextEyebrow: 'DO OUTRO LADO, NOSSA EQUIPE', nextTitle: 'Estamos aqui para ajudar você a dar o próximo passo.',
    steps: [['Ouvimos você', 'Uma primeira ideia ou um plano detalhado: começamos entendendo o que você precisa.'], ['Conversamos juntos', 'Respondemos às suas perguntas e exploramos as opções com você.'], ['Seguimos no seu ritmo', 'Peça orientação, planeje uma celebração ou converse sobre como podemos trabalhar juntos.']],
    location: 'Em Punta Cana, prontos para ouvir você.',
  },
  fr: {
    eyebrow: 'PARLONS-EN', title: 'Tout commence par une conversation.',
    intro: 'Un événement, une collaboration ou simplement une question ? Nous serons ravis de vous écouter. Pas besoin d’avoir tout prévu pour nous écrire.',
    welcome: 'Vos idées. Vos questions. Toujours les bienvenues.',
    direct: 'VOUS PRÉFÉREZ UN ÉCHANGE DIRECT ?', whatsapp: 'Échangeons sur WhatsApp', emailLink: 'Écrivez-nous par email', phoneLink: 'Appelez-nous',
    formEyebrow: 'UN BONJOUR, ET TOUT COMMENCE', formTitle: 'Comment pouvons-nous vous aider ?', formIntro: 'Parlez-nous un peu de vous et de ce que vous avez en tête.',
    purpose: 'Je souhaite…', purposes: ['Poser une question', 'Organiser un événement', 'Proposer une collaboration', 'Parler d’un autre sujet'],
    name: 'Votre nom', namePlaceholder: 'Comment vous appelez-vous ?', email: 'Adresse email', emailPlaceholder: 'vous@exemple.fr',
    phone: 'Téléphone ou WhatsApp', optional: 'facultatif', phoneHint: 'Ajoutez l’indicatif du pays si vous préférez que nous vous contactions ici.',
    message: 'Votre message', messagePlaceholder: 'Partagez votre idée, posez une question ou dites-nous ce dont vous avez besoin. Nous sommes à votre écoute.',
    submit: 'Envoyer mon message', note: 'Seuls votre nom, votre email et votre message sont nécessaires. Ces informations nous permettent de vous répondre.',
    nextEyebrow: 'DE L’AUTRE CÔTÉ, NOTRE ÉQUIPE', nextTitle: 'Nous sommes là pour vous aider à faire le prochain pas.',
    steps: [['Nous vous écoutons', 'Une première idée ou un projet détaillé : nous commençons par comprendre vos besoins.'], ['Nous échangeons', 'Nous répondons à vos questions et explorons les possibilités avec vous.'], ['Nous suivons votre rythme', 'Demandez conseil, préparez une fête ou discutons d’une future collaboration.']],
    location: 'À Punta Cana, prêts à vous écouter.',
  },
};
