// Copy for the contact form fields, which stay in the repo. The rest of the
// contact page is edited in Sanity (one Contact Page document per language).
export const contactContent = {
  "en-US": {
    purpose: "I’d like to…",
    purposes: [
      "Ask a question",
      "Plan an event",
      "Explore a collaboration",
      "Talk about something else",
    ],
    name: "Your name",
    namePlaceholder: "How should we address you?",
    email: "Email address",
    emailPlaceholder: "you@example.com",
    phone: "Phone or WhatsApp",
    optional: "optional",
    phoneHint: "Include your country code if you would like us to contact you here.",
    message: "Your message",
    messagePlaceholder: "Share your idea, ask us a question or tell us what you need. We’re listening.",
    submit: "Send my message",
    note: "Only your name, email and message are required. We use these details to get back to you.",
  },
  es: {
    purpose: "Me gustaría…",
    purposes: [
      "Hacer una pregunta",
      "Organizar un evento",
      "Proponer una colaboración",
      "Conversar sobre otro tema",
    ],
    name: "Tu nombre",
    namePlaceholder: "¿Cómo te llamas?",
    email: "Correo electrónico",
    emailPlaceholder: "tu@ejemplo.com",
    phone: "Teléfono o WhatsApp",
    optional: "opcional",
    phoneHint: "Incluye el código de tu país si prefieres que te contactemos por aquí.",
    message: "Tu mensaje",
    messagePlaceholder: "Comparte tu idea, haznos una pregunta o cuéntanos qué necesitas. Te escuchamos.",
    submit: "Enviar mi mensaje",
    note: "Solo necesitamos tu nombre, correo y mensaje. Usamos estos datos para responderte.",
  },
  pt: {
    purpose: "Gostaria de…",
    purposes: [
      "Fazer uma pergunta",
      "Organizar um evento",
      "Propor uma parceria",
      "Conversar sobre outro assunto",
    ],
    name: "Seu nome",
    namePlaceholder: "Como você se chama?",
    email: "Email",
    emailPlaceholder: "voce@exemplo.com",
    phone: "Telefone ou WhatsApp",
    optional: "opcional",
    phoneHint: "Inclua o código do país se preferir que entremos em contato por aqui.",
    message: "Sua mensagem",
    messagePlaceholder: "Compartilhe sua ideia, faça uma pergunta ou conte-nos do que precisa. Estamos ouvindo.",
    submit: "Enviar minha mensagem",
    note: "Precisamos apenas de nome, email e mensagem. Usamos esses dados para responder a você.",
  },
  fr: {
    purpose: "Je souhaite…",
    purposes: [
      "Poser une question",
      "Organiser un événement",
      "Proposer une collaboration",
      "Parler d’un autre sujet",
    ],
    name: "Votre nom",
    namePlaceholder: "Comment vous appelez-vous ?",
    email: "Adresse email",
    emailPlaceholder: "vous@exemple.fr",
    phone: "Téléphone ou WhatsApp",
    optional: "facultatif",
    phoneHint: "Ajoutez l’indicatif du pays si vous préférez que nous vous contactions ici.",
    message: "Votre message",
    messagePlaceholder: "Partagez votre idée, posez une question ou dites-nous ce dont vous avez besoin. Nous sommes à votre écoute.",
    submit: "Envoyer mon message",
    note: "Seuls votre nom, votre email et votre message sont nécessaires. Ces informations nous permettent de vous répondre.",
  },
};
