import {
  BadgeCheck,
  CalendarCheck,
  CalendarCheck2,
  Camera,
  CarFront,
  Check,
  ClipboardCheck,
  Clock3,
  FileCheck2,
  FileText,
  Flower2,
  GlassWater,
  Globe2,
  Headphones,
  HeartHandshake,
  Home,
  Hotel,
  MapPin,
  MapPinned,
  MessageCircle,
  Music2,
  PartyPopper,
  ShieldCheck,
  Smartphone,
  Sparkles,
  Truck,
  UserRoundCheck,
  Users,
  UsersRound,
  Utensils,
  UtensilsCrossed,
  Video,
  WalletCards,
} from "lucide-react";

// Card icons by the name chosen in Sanity (studio/schemaTypes/objects/iconCard.ts,
// which lists the same names for editors).
export const cardIcons = {
  "badge-check": BadgeCheck,
  "calendar-check": CalendarCheck,
  "calendar-check-2": CalendarCheck2,
  camera: Camera,
  "car-front": CarFront,
  check: Check,
  "clipboard-check": ClipboardCheck,
  "clock-3": Clock3,
  "file-check-2": FileCheck2,
  "file-text": FileText,
  "flower-2": Flower2,
  "glass-water": GlassWater,
  globe: Globe2,
  headphones: Headphones,
  "heart-handshake": HeartHandshake,
  home: Home,
  hotel: Hotel,
  "map-pin": MapPin,
  "map-pinned": MapPinned,
  "message-circle": MessageCircle,
  "music-2": Music2,
  "party-popper": PartyPopper,
  "shield-check": ShieldCheck,
  smartphone: Smartphone,
  sparkles: Sparkles,
  truck: Truck,
  "user-round-check": UserRoundCheck,
  users: Users,
  "users-round": UsersRound,
  utensils: Utensils,
  "utensils-crossed": UtensilsCrossed,
  video: Video,
  "wallet-cards": WalletCards,
};

// The icon for a name, or a check mark for an unknown one.
export const cardIcon = (name) => cardIcons[name] || Check;
