import {
  BadgeCheck,
  CalendarCheck,
  Camera,
  CarFront,
  Check,
  ClipboardCheck,
  FileCheck2,
  Flower2,
  Globe2,
  Headphones,
  HeartHandshake,
  Home,
  Hotel,
  MapPin,
  MapPinned,
  MessageCircle,
  PartyPopper,
  ShieldCheck,
  Sparkles,
  Truck,
  Users,
  Utensils,
  WalletCards,
} from "lucide-react";

// Card icons by the name chosen in Sanity (studio/schemaTypes/objects/iconCard.ts,
// which lists the same names for editors).
export const cardIcons = {
  "badge-check": BadgeCheck,
  "calendar-check": CalendarCheck,
  camera: Camera,
  "car-front": CarFront,
  check: Check,
  "clipboard-check": ClipboardCheck,
  "file-check-2": FileCheck2,
  "flower-2": Flower2,
  globe: Globe2,
  headphones: Headphones,
  "heart-handshake": HeartHandshake,
  home: Home,
  hotel: Hotel,
  "map-pin": MapPin,
  "map-pinned": MapPinned,
  "message-circle": MessageCircle,
  "party-popper": PartyPopper,
  "shield-check": ShieldCheck,
  sparkles: Sparkles,
  truck: Truck,
  users: Users,
  utensils: Utensils,
  "wallet-cards": WalletCards,
};

// The icon for a name, or a check mark for an unknown one.
export const cardIcon = (name) => cardIcons[name] || Check;
