import React, { useEffect, useRef, useState } from 'react';
import './weddingExperience.css';
import media from './indianWeddingMedia.json';

export const uxCopy = {
  'en-US': {western:'Western weddings', indian:'South Asian weddings', explore:'Explore the celebration', title:'Indian Wedding Planner in Punta Cana', gallery:'A real Indian wedding in Punta Cana', intro:'Your traditions shape the celebration. We bring the people, places and plans together, so you can be present for every moment.', films:'Two glimpses of the celebration', ceremony:'The ceremony', evening:'The evening celebration', play:'Play film', close:'Close gallery', previous:'Previous photo', next:'Next photo', open:'Open photo', services:'Choose your wedding planning service', undecided:'We would like your guidance', story:'From quiet details to shared celebrations', westernText:'We coordinate your venue, suppliers and wedding day around the celebration you imagine.', indianText:'We plan the details and logistics across your wedding celebrations, with your family’s traditions at the heart.', team:'Our team, beside you', teamText:'With Grecia leading our planning team, we listen, coordinate and stay close throughout your wedding journey.'},
  es: {western:'Bodas occidentales', indian:'Bodas surasiáticas', explore:'Explora la celebración', title:'Planificación de bodas indias en Punta Cana', gallery:'Una boda india real en Punta Cana', intro:'Sus tradiciones dan forma a la celebración. Nosotros coordinamos las personas, los espacios y los planes para que puedan vivir cada momento.', films:'Dos miradas a la celebración', ceremony:'La ceremonia', evening:'La celebración nocturna', play:'Reproducir vídeo', close:'Cerrar galería', previous:'Foto anterior', next:'Foto siguiente', open:'Ampliar foto', services:'Elijan su servicio de planificación de bodas', undecided:'Nos gustaría recibir orientación', story:'De los pequeños detalles a la celebración compartida', westernText:'Coordinamos el lugar, los proveedores y el día de la boda alrededor de la celebración que imaginan.', indianText:'Planificamos los detalles y la logística de sus celebraciones, con las tradiciones de su familia en el centro.', team:'Nuestro equipo, a su lado', teamText:'Con Grecia al frente de nuestro equipo, escuchamos, coordinamos y los acompañamos durante la preparación y la celebración de su boda.'},
  pt: {western:'Casamentos ocidentais', indian:'Casamentos sul-asiáticos', explore:'Explore a celebração', title:'Planejamento de casamentos indianos em Punta Cana', gallery:'Um casamento indiano real em Punta Cana', intro:'Suas tradições dão forma à celebração. Nós coordenamos as pessoas, os espaços e os planos para que vocês vivam cada momento.', films:'Dois olhares sobre a celebração', ceremony:'A cerimônia', evening:'A celebração à noite', play:'Reproduzir vídeo', close:'Fechar galeria', previous:'Foto anterior', next:'Próxima foto', open:'Ampliar foto', services:'Escolham seu serviço de planejamento', undecided:'Gostaríamos de receber orientação', story:'Dos pequenos detalhes à celebração compartilhada', westernText:'Coordenamos o local, os fornecedores e o dia do casamento em torno da celebração que vocês imaginam.', indianText:'Planejamos os detalhes e a logística das celebrações, respeitando as tradições da sua família.', team:'Nossa equipe, ao seu lado', teamText:'Com Grecia à frente da nossa equipe, ouvimos, coordenamos e acompanhamos vocês durante o planejamento e a celebração.'},
  fr: {western:'Mariages occidentaux', indian:'Mariages sud-asiatiques', explore:'Explorez la célébration', title:'Organisation de mariages indiens à Punta Cana', gallery:'Un véritable mariage indien à Punta Cana', intro:'Vos traditions façonnent la célébration. Nous coordonnons les personnes, les lieux et les préparatifs pour que vous profitiez de chaque instant.', films:'Deux regards sur la célébration', ceremony:'La cérémonie', evening:'La célébration en soirée', play:'Lire la vidéo', close:'Fermer la galerie', previous:'Photo précédente', next:'Photo suivante', open:'Agrandir la photo', services:'Choisissez votre accompagnement', undecided:'Nous aimerions être conseillés', story:'Des petits détails aux moments partagés', westernText:'Nous coordonnons le lieu, les prestataires et le jour du mariage autour de la célébration que vous imaginez.', indianText:'Nous organisons les détails et la logistique de vos célébrations en respectant les traditions de votre famille.', team:'Notre équipe, à vos côtés', teamText:'Avec Grecia à la tête de notre équipe, nous vous écoutons et vous accompagnons tout au long des préparatifs et de la célébration.'},
};
const descriptions = {
 'en-US':['The couple on the beach at sunset','The couple with Grecia at their wedding ceremony','Bridal portrait beneath the palms','Henna and jewelry details','The bride with Grecia during the celebration','The bride arriving with family','Wedding ceremony surrounded by family','The groom arriving on horseback','Grecia with the bride in the evening','The couple during their wedding ceremony','The couple sharing a wedding ritual','The couple celebrating with family','Grecia with the bride at the resort','The couple together beside the sea'],
 es:['La pareja en la playa al atardecer','La pareja con Grecia en su ceremonia de boda','Retrato de la novia entre las palmeras','Detalles de henna y joyería','La novia con Grecia durante la celebración','La llegada de la novia con su familia','Ceremonia de boda rodeados de familiares','La llegada del novio a caballo','Grecia con la novia durante la noche','La pareja durante su ceremonia de boda','La pareja compartiendo un ritual de boda','La pareja celebrando con su familia','Grecia con la novia en el resort','La pareja junto al mar'],
 pt:['O casal na praia ao pôr do sol','O casal com Grecia na cerimônia de casamento','Retrato da noiva entre as palmeiras','Detalhes de henna e joias','A noiva com Grecia durante a celebração','A chegada da noiva com a família','Cerimônia de casamento com familiares','A chegada do noivo a cavalo','Grecia com a noiva à noite','O casal durante a cerimônia de casamento','O casal compartilhando um ritual de casamento','O casal celebrando com a família','Grecia com a noiva no resort','O casal à beira-mar'],
 fr:['Le couple sur la plage au coucher du soleil','Le couple avec Grecia lors de la cérémonie','Portrait de la mariée parmi les palmiers','Détails du henné et des bijoux','La mariée avec Grecia pendant la célébration','L’arrivée de la mariée avec sa famille','La cérémonie entourée des familles','L’arrivée du marié à cheval','Grecia avec la mariée en soirée','Le couple pendant la cérémonie de mariage','Le couple partageant un rituel de mariage','Le couple célébrant avec sa famille','Grecia avec la mariée au resort','Le couple au bord de la mer'],
};
export const getIndianPhotos = language => media.map((asset,index)=>({...asset,description:`${(descriptions[language]||descriptions['en-US'])[index]} — Punta Cana`}));
export function IndianImage({asset,className='',alt=''}) {
  return <img className={className} src={asset.thumb} srcSet={`${asset.thumb} ${Math.round(asset.width * 640 / 1440)}w, ${asset.url} ${asset.width}w`} sizes="(max-width: 640px) 85vw, 430px" width={asset.width} height={asset.height} loading="lazy" decoding="async" alt={asset.description||alt} title={asset.description||alt}/>;
}
export function WeddingGallery({images,copy,renderImage,label}) {
  const [active,setActive]=useState(0), [opened,setOpened]=useState(false);
  const [slide,setSlide]=useState(0);
  const dialog=useRef(null), touch=useRef(null),rail=useRef(null);
  const go=direction=>{const next=Math.max(0,Math.min(images.length-1,slide+direction));const child=rail.current.children[next];rail.current.scrollTo({left:child.offsetLeft,behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});};
  useEffect(()=>{if(!opened)return;const old=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=old;};},[opened]);
  const move=direction=>setActive(value=>(value+direction+images.length)%images.length);
  const close=()=>{dialog.current.close();setOpened(false);};
  return <>
    <div className="wp-carousel-controls"><span aria-live="polite">{slide+1} / {images.length}</span><button type="button" onClick={()=>go(-1)} disabled={slide===0} aria-label={copy.previous}>←</button><button type="button" onClick={()=>go(1)} disabled={slide===images.length-1} aria-label={copy.next}>→</button></div>
    <div className="wp-rail" ref={rail} role="region" aria-label={label} tabIndex={0} onKeyDown={e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();go(e.key==='ArrowRight'?1:-1);}}} onScroll={()=>{const cards=[...rail.current.children];const left=rail.current.scrollLeft;let nearest=0;cards.forEach((card,i)=>{if(Math.abs(card.offsetLeft-left)<Math.abs(cards[nearest].offsetLeft-left))nearest=i;});setSlide(nearest);}}>{images.map((asset,index)=><button className="wp-photo" type="button" key={asset.id||index} aria-label={`${copy.open}: ${label} ${index+1}`} onClick={()=>{setActive(index);setOpened(true);dialog.current.showModal();}}>{renderImage(asset)}<span className="wp-photo-hint" aria-hidden="true">↗</span></button>)}</div>
    <dialog ref={dialog} className="wp-dialog" aria-label={label} onClose={()=>setOpened(false)} onClick={event=>{if(event.target===event.currentTarget)close();}} onKeyDown={event=>{if(event.key==='ArrowRight'){event.preventDefault();move(1);}if(event.key==='ArrowLeft'){event.preventDefault();move(-1);}}}>
      <button type="button" className="wp-dialog-close" onClick={close} aria-label={copy.close}>×</button>
      {opened&&<div className="wp-view" onTouchStart={e=>{touch.current=e.touches[0].clientX;}} onTouchEnd={e=>{if(touch.current!==null){const delta=e.changedTouches[0].clientX-touch.current;if(Math.abs(delta)>60)move(delta<0?1:-1);touch.current=null;}}}>{renderImage(images[active],true)}</div>}
      <div className="wp-dialog-controls"><button type="button" onClick={()=>move(-1)} aria-label={copy.previous}>←</button><span aria-live="polite">{active+1} / {images.length}</span><button type="button" onClick={()=>move(1)} aria-label={copy.next}>→</button></div>
    </dialog>
  </>;
}
export function WeddingFilms({copy}) {
  const [active,setActive]=useState(null);
  return <div className="wp-films">{[copy.ceremony,copy.evening].map((title,index)=>{const file=`/media/indian-wedding/indian-wedding-punta-cana-${index===0?'ceremony':'evening'}`;return <figure key={title}><div className="wp-film">{active===index?<video controls autoPlay muted playsInline preload="none" poster={`${file}.webp`} aria-label={`${title} — Punta Cana`} title={`${title} — Punta Cana`} src={`${file}.mp4`}/>:<button type="button" onClick={()=>setActive(index)} aria-label={`${copy.play}: ${title}`}><img src={`${file}.webp`} width="540" height="960" loading="lazy" alt={`${title} — Punta Cana`} title={`${title} — Punta Cana`}/><span className="wp-play" aria-hidden="true">▷</span></button>}</div><figcaption>{title}</figcaption></figure>;})}</div>;
}

