import React, { useEffect, useRef, useState } from 'react';
import './weddingExperience.css';

export const uxCopy = {
  'en-US': {western:'Western weddings', indian:'South Asian weddings', explore:'Explore the celebration', title:'Indian Wedding Planner in Punta Cana', gallery:'A real Indian wedding in Punta Cana', intro:'Your traditions shape the celebration. We bring the people, places and plans together, so you can be present for every moment.', films:'Two glimpses of the celebration', ceremony:'The ceremony', evening:'The evening celebration', play:'Play film', close:'Close gallery', previous:'Previous photo', next:'Next photo', open:'Open photo', services:'Choose your wedding planning service', undecided:'We would like your guidance', story:'From quiet details to shared celebrations', westernText:'We coordinate your venue, suppliers and wedding day around the celebration you imagine.', indianText:'We plan the details and logistics across your wedding celebrations, with your family’s traditions at the heart.', team:'Our team, beside you', teamText:'With Grecia leading our planning team, we listen, coordinate and stay close throughout your wedding journey.'},
  es: {western:'Bodas occidentales', indian:'Bodas surasiáticas', explore:'Explora la celebración', title:'Planificación de bodas indias en Punta Cana', gallery:'Una boda india real en Punta Cana', intro:'Sus tradiciones dan forma a la celebración. Nosotros coordinamos las personas, los espacios y los planes para que puedan vivir cada momento.', films:'Dos miradas a la celebración', ceremony:'La ceremonia', evening:'La celebración nocturna', play:'Reproducir vídeo', close:'Cerrar galería', previous:'Foto anterior', next:'Foto siguiente', open:'Ampliar foto', services:'Elijan su servicio de planificación de bodas', undecided:'Nos gustaría recibir orientación', story:'De los pequeños detalles a la celebración compartida', westernText:'Coordinamos el lugar, los proveedores y el día de la boda alrededor de la celebración que imaginan.', indianText:'Planificamos los detalles y la logística de sus celebraciones, con las tradiciones de su familia en el centro.', team:'Nuestro equipo, a su lado', teamText:'Con Grecia al frente de nuestro equipo, escuchamos, coordinamos y los acompañamos durante la preparación y la celebración de su boda.'},
  pt: {western:'Casamentos ocidentais', indian:'Casamentos sul-asiáticos', explore:'Explore a celebração', title:'Planejamento de casamentos indianos em Punta Cana', gallery:'Um casamento indiano real em Punta Cana', intro:'Suas tradições dão forma à celebração. Nós coordenamos as pessoas, os espaços e os planos para que vocês vivam cada momento.', films:'Dois olhares sobre a celebração', ceremony:'A cerimônia', evening:'A celebração à noite', play:'Reproduzir vídeo', close:'Fechar galeria', previous:'Foto anterior', next:'Próxima foto', open:'Ampliar foto', services:'Escolham seu serviço de planejamento', undecided:'Gostaríamos de receber orientação', story:'Dos pequenos detalhes à celebração compartilhada', westernText:'Coordenamos o local, os fornecedores e o dia do casamento em torno da celebração que vocês imaginam.', indianText:'Planejamos os detalhes e a logística das celebrações, respeitando as tradições da sua família.', team:'Nossa equipe, ao seu lado', teamText:'Com Grecia à frente da nossa equipe, ouvimos, coordenamos e acompanhamos vocês durante o planejamento e a celebração.'},
  fr: {western:'Mariages occidentaux', indian:'Mariages sud-asiatiques', explore:'Explorez la célébration', title:'Organisation de mariages indiens à Punta Cana', gallery:'Un véritable mariage indien à Punta Cana', intro:'Vos traditions façonnent la célébration. Nous coordonnons les personnes, les lieux et les préparatifs pour que vous profitiez de chaque instant.', films:'Deux regards sur la célébration', ceremony:'La cérémonie', evening:'La célébration en soirée', play:'Lire la vidéo', close:'Fermer la galerie', previous:'Photo précédente', next:'Photo suivante', open:'Agrandir la photo', services:'Choisissez votre accompagnement', undecided:'Nous aimerions être conseillés', story:'Des petits détails aux moments partagés', westernText:'Nous coordonnons le lieu, les prestataires et le jour du mariage autour de la célébration que vous imaginez.', indianText:'Nous organisons les détails et la logistique de vos célébrations en respectant les traditions de votre famille.', team:'Notre équipe, à vos côtés', teamText:'Avec Grecia à la tête de notre équipe, nous vous écoutons et vous accompagnons tout au long des préparatifs et de la célébration.'},
};
export const indianPhotos = ['126','133','142','229','251','266','281','283','316','103','56','319'].map(id=>({id,url:`/media/indian-wedding/${id}-1440.webp`,thumb:`/media/indian-wedding/${id}-640.webp`}));
export function IndianImage({asset,className='',alt=''}) {
  return <img className={className} src={asset.thumb} srcSet={`${asset.thumb} 640w, ${asset.url} 1440w`} sizes="(max-width: 640px) 90vw, 50vw" width="1440" height="960" loading="lazy" decoding="async" alt={alt}/>;
}
export function WeddingGallery({images,copy,renderImage,label}) {
  const [active,setActive]=useState(0), [opened,setOpened]=useState(false);
  const dialog=useRef(null), touch=useRef(null);
  useEffect(()=>{if(!opened)return;const old=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=old;};},[opened]);
  const move=direction=>setActive(value=>(value+direction+images.length)%images.length);
  const close=()=>{dialog.current.close();setOpened(false);};
  return <>
    <div className="wp-mosaic">{images.map((asset,index)=><button className="wp-photo" type="button" key={asset.id||index} aria-label={`${copy.open}: ${label} ${index+1}`} onClick={()=>{setActive(index);setOpened(true);dialog.current.showModal();}}>{renderImage(asset)}<span className="wp-photo-hint" aria-hidden="true">↗</span></button>)}</div>
    <dialog ref={dialog} className="wp-dialog" aria-label={label} onClose={()=>setOpened(false)} onClick={event=>{if(event.target===event.currentTarget)close();}} onKeyDown={event=>{if(event.key==='ArrowRight'){event.preventDefault();move(1);}if(event.key==='ArrowLeft'){event.preventDefault();move(-1);}}}>
      <button type="button" className="wp-dialog-close" onClick={close} aria-label={copy.close}>×</button>
      {opened&&<div className="wp-view" onTouchStart={e=>{touch.current=e.touches[0].clientX;}} onTouchEnd={e=>{if(touch.current!==null){const delta=e.changedTouches[0].clientX-touch.current;if(Math.abs(delta)>60)move(delta<0?1:-1);touch.current=null;}}}>{renderImage(images[active],true)}</div>}
      <div className="wp-dialog-controls"><button type="button" onClick={()=>move(-1)} aria-label={copy.previous}>←</button><span aria-live="polite">{active+1} / {images.length}</span><button type="button" onClick={()=>move(1)} aria-label={copy.next}>→</button></div>
    </dialog>
  </>;
}
export function WeddingFilms({copy}) {
  const [active,setActive]=useState(null);
  return <div className="wp-films">{[copy.ceremony,copy.evening].map((title,index)=><figure key={title}><div className="wp-film">{active===index?<video controls autoPlay muted playsInline preload="none" poster={`/media/indian-wedding/reel-${index+1}.webp`} aria-label={title} src={`/media/indian-wedding/reel-${index+1}.mp4`}/>:<button type="button" onClick={()=>setActive(index)} aria-label={`${copy.play}: ${title}`}><img src={`/media/indian-wedding/reel-${index+1}.webp`} width="540" height="960" loading="lazy" alt=""/><span className="wp-play" aria-hidden="true">▷</span></button>}</div><figcaption>{title}</figcaption></figure>)}</div>;
}
